Repository zalando-incubator/cluster-lifecycle-manager, pull requests merged in 2024-02, with the labels that each got.

#747 fix linter errors
  controller/cluster_list.go
  controller/cluster_list_test.go
  pkg/updatestrategy/aws_asg.go
  pkg/updatestrategy/aws_ec2.go
  pkg/updatestrategy/drain_test.go
  pkg/updatestrategy/node_pool_manager_test.go
  provisioner/aws.go
  provisioner/clusterpy.go
  provisioner/clusterpy_test.go
  provisioner/remote_files_test.go
Labels: bug

#743 add template functions for dynamic resource scaling
  provisioner/clusterpy.go
  provisioner/clusterpy_test.go
  provisioner/node_pools.go
  provisioner/remote_files.go
  provisioner/template.go
  provisioner/template_test.go
Labels: enhancement

#748 Update client-go/kubectl to Kubernetes v1.25
  .github/workflows/ci.yaml
  Dockerfile
  Makefile
  cmd/clm/main.go
  config/config.go
  go.mod
  go.sum
Labels: minor

#749 Make decommissioning more graceful
  provisioner/clusterpy.go
Labels: minor
