Repository zalando-incubator/cluster-lifecycle-manager, pull requests merged in 2024-08, with the labels that each got.

#777 Add EKS support
  cmd/clm/main.go
  controller/controller.go
  controller/controller_test.go
  go.mod
  go.sum
  pkg/aws/eks/token.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_test.go
  pkg/updatestrategy/node_pool_manager.go
  provisioner/aws.go
  provisioner/clusterpy.go
  provisioner/clusterpy_test.go
  provisioner/node_pools.go
  provisioner/provisioner.go
  provisioner/provisioner_test.go
  provisioner/stdout.go
  provisioner/template.go
  provisioner/template_test.go
  provisioner/zalando_aws.go
  provisioner/zalando_eks.go
Labels: major

#801 Update Cluster Registry entry when provisioning an EKS cluster.
  cmd/clm/main.go
  controller/controller.go
  controller/controller_test.go
  go.mod
  go.sum
  provisioner/aws_test.go
  provisioner/clusterpy.go
  provisioner/node_pools.go
  provisioner/provisioner.go
  provisioner/zalando_eks.go
  provisioner/zalando_eks_test.go
  registry/file.go
  registry/http.go
  registry/http_test.go
  registry/registry.go
  registry/static.go
Labels: minor

#802 Only update EKS config items when needed.
  controller/controller_test.go
  provisioner/zalando_eks.go
  provisioner/zalando_eks_test.go
  registry/file.go
  registry/http.go
  registry/http_test.go
  registry/registry.go
  registry/static.go
Labels: bug, minor

#803 Get EKS endpoint data from Config Items
  provisioner/zalando_eks.go
Labels: minor

#804 Add OIDC issuer url as config item to the cluster
  provisioner/aws.go
  provisioner/zalando_eks.go
  provisioner/zalando_eks_test.go
  registry/http_test.go
Labels: minor
